### PR TITLE
Create sudokumaster.py

### PR DESCRIPTION
**Pull request by Drucephus**
Building on the print_board() function, this introduces the get_board() function that lets a user input a sudoku board.

Make sure this is confirmed AFTER the print-board-function branch

### CODE REVIEW

**Review by ajithvemasani — APPROVED** [review]

**Review by Wickramasingh — APPROVED** [review]
Approved. No changes needed.

**Review by SreehariR97 — APPROVED** [review]
Looks good to me no changes required.

**Comment by gragiri** [comment]
Looks good to me no changes required.

**Review by spogaku1 — APPROVED** [review]
Every thing seems good..No change required.

**Comment by BellTr3** [comment]
every thing is good

**Comment by BellTr3** [comment]
every thing is good

**Pull request merged**
